### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by zcrowe** [xyu/heroku-wp#130] opened 2017-06-04 01:01 UTC
Hello :)

Firstly - thanks for the tremendous work on this!

I'm just experimenting with it atm, but during install:

```
heroku run wp core install \
    --url=pottery-test.herokuapp.com \
    --title="Pottery Things" \
    --admin_user="admin" \
    --admin_password="correct-horse-battery-staple" \
    --admin_email="nope@notreal.com"
```

I'm getting this error in the shell:

```
WordPress database error Table 'iamfav80sl724b1g.wp_options' doesn't exist for query INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('uninstall_plugins', 'a:2:{i:0;b:0;s:45:\"secure-db-connection/secure-db-connection.php\";s:32:\"WP_SecureDBConnection::uninstall\";}', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) made by include_once('/app/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), include_once('/mu-plugins/secure-db-connection/secure-db-connection.php'), register_uninstall_hook, update_option, add_option
sh: 1: -t: not found
```
I've checked the database, and wp_options does exist, and does appear to be populated.

I tried to run:

`INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('uninstall_plugins', 'a:2:{i:0;b:0;s:45:\"secure-db-connection/secure-db-connection.php\";s:32:\"WP_SecureDBConnection::uninstall\";}', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
`
Against the DB directly, and this caused no errors.

On visiting the site: http://pottery-test.herokuapp.com/ I get the following:

`Fatal error: Uncaught Error: Call to undefined function WP_CLI\Dispatcher\get_path() in /app/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:49 Stack trace: #0 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(37): WP_CLI\Runner->register_early_invoke('before_wp_load', Object(WP_CLI\Dispatcher\Subcommand)) #1 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(20): WP_CLI\Dispatcher\CompositeCommand->__construct(Object(WP_CLI\Dispatcher\RootCommand), 'server', Object(WP_CLI\DocParser)) #2 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(73): WP_CLI\Dispatcher\Subcommand->__construct(Object(WP_CLI\Dispatcher\RootCommand), 'server', Object(WP_CLI\DocParser), Object(Closure)) #3 /app/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(34): WP_CLI\Dispatcher\CommandFactory::create_subcommand(Object(WP_CLI\Dispatcher\RootCommand), 'server', Array, Object(ReflectionMethod)) #4 /app/vendor/wp-cli/wp-cli/php/class-wp-cli.php(466): WP_CLI\Dispatcher\CommandFactory::create('serve in /app/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php on line 49`

Am I being super dumb - or have I found a legitimate bug :)

Thanks!

**Comment by zcrowe** [comment] 2017-06-07 05:55
So - for reasons unknown, this just started to work for me, currently suspect blip with heroku :)

**Comment by mitramejia** [comment] 2018-01-13 01:45
Got the same error running `wp core install` but no error when visiting the site

**Comment by p3v9d5ui** [comment] 2018-03-12 15:42
I also got this error, but found that replacing the double quotes worked for me, e.g.:

`heroku run wp core install --url='xxx.xxxx.xxx' --title='some title' --admin_user='admin' --admin_password='xxxxx' --admin_email='xxxx@xxxx.xxx'`

**Comment by xyu** [comment] 2018-06-30 20:59
Heroku WP depends on the [Maria DB add on from JawsDB](https://elements.heroku.com/addons/jawsdb-maria). That add-on is one of the first ones provisioned however the API for it does not give any indication on if the database has been setup or not. Normally provisioning Heroky Redis, which does have a wait parameter, takes much longer and happens after we initialize the provisioning of Maria DB so everything works out fine.

I guess in these instances JawsDB was having issues / delays so the database was not provisioned in time / you all are too fast at the keyboard. ;)

Going to mark this as closed as the problem is likely transient.

**Closed by xyu** 2018-06-30 20:59 UTC

**Comment by evanjmg** [comment] 2019-12-25 20:58
Getting the same issue now in Dec 2019. Anyone get the same?

**Comment by evanjmg** [comment] 2019-12-25 21:04
just entered it on the website instead of cli and it worked
